### ISSUE TITLE
building on mono?

### ISSUE THREAD

**Issue by tomgjones** [casascius/Bitcoin-Address-Utility#5] opened 2012-09-05 20:55 UTC
This looks like it's written to be build using the MS toolset.  I tried to build this on Linux with "xbuild BtcAddress.csproj" and l and got the following.  Any idea how to get this buildable on Linux?

Build FAILED.

Warnings:

/home/tom/co/Bitcoin-Address-Utility/BtcAddress.csproj (default targets) ->
/usr/lib/mono/3.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

```
    /usr/lib/mono/3.5/Microsoft.Common.targets:  warning : Reference 'System.Deployment' not resolved
```

Errors:

/home/tom/co/Bitcoin-Address-Utility/BtcAddress.csproj (default targets) ->
/usr/lib/mono/3.5/Microsoft.CSharp.targets (CoreCompile target) ->

```
    Form1.cs(26,2): error CS1519: Unexpected symbol `<<' in class, struct, or interface member declaration
    Form1.cs(28,2): error CS1519: Unexpected symbol `==' in class, struct, or interface member declaration
    Form1.cs(32,20): error CS1519: Unexpected symbol `void' in class, struct, or interface member declaration

     1 Warning(s)
     3 Error(s)
```

Time Elapsed 00:00:00.5686540

**Comment by enmaku** [comment] 2012-09-06 00:04
This actually seems to be an issue with this specific chunk of code between lines 26 and 30:

```
<<<<<<< HEAD
        // a different test
=======
    //test
>>>>>>> 1f3595704784ba9fd03d9e0f1f425b6f458c62cb
```

I have no idea why that's there but I've confirmed that it builds properly in Windows without it, though I've never actually tested in xbuild/mono. The good news is that the same lines throw the same errors in Windows so removing them before building should fix this for you. I'm removing them from the copy hosted here now, as they certainly don't belong here.

**Comment by enmaku** [comment] 2012-09-06 00:07
I've pushed the changes to the git repo. Let me know if that fixes the issue so I can close this one out :)

**Comment by tomgjones** [comment] 2012-09-06 12:29
On Wed, Sep 05, 2012 at 05:04:33PM -0700, enmaku wrote:

> This actually seems to be an issue with this specific chunk of code 
> between lines 26 and 30:
> 
> ```
> <<<<<<< HEAD
>       // a different test
> =======
>   //test
> >>>>>>> 1f3595704784ba9fd03d9e0f1f425b6f458c62cb
> ```
> 
> I have no idea why that's there 

Ah, those look like version control conflict markers, and it looks
like commit 2ed3d41e accidentally committed the conflict instead of
resolving it.

Thanks for fixing this - I'll try the build again later.

  Tom.

**Comment by casascius** [comment] 2012-12-07 06:07
I think this is resolved

**Closed as completed by casascius** 2012-12-07 06:07 UTC
